// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// source: github.com/dogmatiq/testkit/internal/fixtures/protobuf.proto

package fixtures

import proto "google.golang.org/protobuf/proto"

type ProtoMessageBuilder struct {
	prototype ProtoMessage
}

// NewProtoMessageBuilder returns a builder that constructs [ProtoMessage] messages.
func NewProtoMessageBuilder() *ProtoMessageBuilder {
	return &ProtoMessageBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ProtoMessageBuilder) From(x *ProtoMessage) *ProtoMessageBuilder {
	proto.Reset(&b.prototype)
	b.prototype.SetValue(x.GetValue())
	return b
}

// Build returns a new [ProtoMessage] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ProtoMessageBuilder) Build() *ProtoMessage {
	m := &ProtoMessage{}
	m.SetValue(b.prototype.GetValue())
	return m
}

// WithValue configures the builder to set the Value field to v,
// then returns b.
func (b *ProtoMessageBuilder) WithValue(v string) *ProtoMessageBuilder {
	b.prototype.SetValue(v)
	return b
}
