// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: github.com/dogmatiq/testkit/internal/fixtures/protobuf.proto

package fixtures

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProtoMessage is a Dogma message implemented as a Protocol Buffers message.
type ProtoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMessage) Reset() {
	*x = ProtoMessage{}
	mi := &file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMessage) ProtoMessage() {}

func (x *ProtoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMessage.ProtoReflect.Descriptor instead.
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDesc = "" +
	"\n" +
	"<github.com/dogmatiq/testkit/internal/fixtures/protobuf.proto\x12\x19dogmatiq.testkit.fixtures\"$\n" +
	"\fProtoMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB/Z-github.com/dogmatiq/testkit/internal/fixturesb\x06proto3"

var (
	file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDescData []byte
)

func file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDesc), len(file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDescData
}

var file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_goTypes = []any{
	(*ProtoMessage)(nil), // 0: dogmatiq.testkit.fixtures.ProtoMessage
}
var file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_init() }
func file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_init() {
	if File_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDesc), len(file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto = out.File
	file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_goTypes = nil
	file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_depIdxs = nil
}
