// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/dogmatiq/testkit/internal/fixtures/protobuf.proto

package fixtures

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProtoMessage is a Dogma message implemented as a Protocol Buffers message.
type ProtoMessage struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value       *string                `protobuf:"bytes,1,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProtoMessage) Reset() {
	*x = ProtoMessage{}
	mi := &file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMessage) ProtoMessage() {}

func (x *ProtoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProtoMessage) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *ProtoMessage) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ProtoMessage) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProtoMessage) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Value = nil
}

type ProtoMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value *string
}

func (b0 ProtoMessage_builder) Build() *ProtoMessage {
	m0 := &ProtoMessage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

var File_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDesc = "" +
	"\n" +
	"<github.com/dogmatiq/testkit/internal/fixtures/protobuf.proto\x12\x19dogmatiq.testkit.fixtures\"$\n" +
	"\fProtoMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB/Z-github.com/dogmatiq/testkit/internal/fixturesb\beditionsp\xe9\a"

var file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_goTypes = []any{
	(*ProtoMessage)(nil), // 0: dogmatiq.testkit.fixtures.ProtoMessage
}
var file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_init() }
func file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_init() {
	if File_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDesc), len(file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto = out.File
	file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_goTypes = nil
	file_github_com_dogmatiq_testkit_internal_fixtures_protobuf_proto_depIdxs = nil
}
